version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpa_operations_app
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 RPA_OPERATIONS.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      # Base de Datos
      - USE_REMOTE_DB=${USE_REMOTE_DB}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      # Correo
      - EMAIL=${EMAIL}
      - PASSWORD_EMAIL=${PASSWORD_EMAIL}
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
  media_volume: